name: Markdown Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  markdownlint:
    uses: A-TownChain-Okosystems/.github/.github/workflows/reusable-markdownlint.yml@61f19417e181796aef529bccea8e7c6461fce0ab
    permissions:
      contents: read
